# This is a build process is purposefully naive to serve as an example.

presentation:
	pdflatex presentation.tex
	bibtex presentation
	pdflatex presentation.tex

report:
	pdflatex report.tex
	bibtex report
	pdflatex report.tex
